apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: DevOpsCICD
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: mertcihanbayir/postgres:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopscicd
  template:
    metadata:
      labels:
        app: devopscicd
    spec:
      containers:
        - name: devopscicd
          image: mertcihanbayir/devopscicd:latest
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VERSION
          ports:
            - containerPort: 8080
