apiVersion: V1
kind: Service
metadata:
  name: postgresql
  labels:
    app: DevOpsCICD
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: potgresql
    spec:
      containers:
        - name: DevOpsCICD
          image: gcr.io/google #değiştir
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DATABASE
              value: postgres
          ports:
            - containerPort: 5432
              name: postgresql