version: '3.8'

services:
  spring-boot-app:
    container_name: springapp
    image: dnspring
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    restart: always
    networks:
      - sbnet

  postgres-db:
    container_name: postgresdb
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - sbnet

networks:
  sbnet:
    external: true
