pipeline {
    agent any

    environment {
        PATH = "/mnt/c/Program Files/Gradle/gradle-8.7/bin:${env.PATH}"
        registry = "mertcihanbayir/devopscicd"
        registryCredentials = 'credentialid'
        dockerImage = 'devopscicd:latest'
        version = "v${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout gradle and java') {
            steps {
                sh 'gradle --version'
                sh 'java --version'
            }
        }
        stage('Check my project from github') {
            steps {
                git 'https://github.com/seyma-altiparmak/DevOpsCICD.git'
            }
        }
        stage('Building jar file') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew clean build'
            }
        }
        stage('Build Docker image') {
            steps {
                sh 'docker build -t ${registry}:latest .'
            }
        }
        stage('Tag Docker Image') {
            steps {
                sh 'docker tag ${registry}:latest ${registry}:${version}'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                retry(3) {
                    sh 'echo 74An855855. | docker login --username mertcihanbayir --password-stdin'
                }
            }
        }
        stage('Push Docker Image to the hub') {
            steps {
                sh 'docker push ${registry}:${version}'
            }
        }
        stage('Update Kubernetes Deployment') {
            steps {
                script {
                    // Kubeconfig dosyasını echo komutları ile oluştur
                    sh '''
                    cat <<EOF > kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZIVENDQXdXZ0F3SUJBZ0lRU1J3S3VsSnJCVW1Pbkt6dTRWUGp1REFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TkRBMU1UWXhNVEl4TlRWYUZ3MHlOakExTVRZeE1UTXhOVFZhTURBeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1SVXdFd1lEVlFRREV3eHRZWE4wWlhKamJHbGxiblF3CmdnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUQ2d1d4c3FOU2UwZzJEbVJ3SC9qMDQKUnJRMWJjL3p3a1JLanJsRG83YVdmTmVUS3JXK2c1UVI5YzNpaWk1MW5NdVVIUEpabWJoUEdjMjYvWEdHRkZFbAowZXpndGpva1IwR2UxNzVLQXBhOU50alhuWE14bmxua1dQSjhNWTRmenYvVnpWeWRVd0RRbDBHZkh2dVI0SVdjCks3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQ
    server: https://devops-aks-dns-r3pjx0z0.hcp.northeurope.azmk8s.io
  name: devops-aks
contexts:
- context:
    cluster: devops-aks
    user: clusterUser_azuredevops_devops-aks
  name: devops-aks
current-context: devops-aks
kind: Config
preferences: {}
users:
- name: clusterUser_azuredevops_devops-aks
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZIVENDQXdXZ0F3SUJBZ0lRU1J3S3VsSnJCVW1Pbkt6dTRWUGp1REFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TkRBMU1UWXhNVEl4TlRWYUZ3MHlOakExTVRZeE1UTXhOVFZhTURBeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1SVXdFd1lEVlFRREV3eHRZWE4wWlhKamJHbGxiblF3CmdnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUQ2d1d4c3FOU2UwZzJEbVJ3SC9qMDQKUnJRMWJjL3p3a1JLanJsRG83YVdmTmVUS3JXK2c1UVI5YzNpaWk1MW5NdVVIUEpabWJoUEdjMjYvWEdHRkZFbAowZXpndGpva1IwR2UxNzVLQXBhOU50alhuWE14bmxua1dQSjhNWTRmenYvVnpWeWRVd0RRbDBHZkh2dVI0SVdjCks3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQClo3V3k4cFhvTDdEb0NXYWxUMzhIZWIyTkNVcFZjd1BsK0xxbUtoQUFGclhqbEdtTGUvUmpmTW5RaXUvZ3owUmYKY2FNYUtWd25uSU9FY3BMWFl2cHVyVTQyeDJwWCtnM3ZFMThJbWQyUm9OVElmeHFzUEFlRXBIQklEMzVKME5ydApReXpnYkRheS92cnI4S2NzR1B3TXV4eE94OU9JWVNpZFM2cS9KMWJNREQ2cE95OU1UNmpTK1doMFRTWk1LaTNQ
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS2dJQkFBS0NBZ0VBK3NGc2JLalVudElOZzVrY0IvNDlPRWEwTlczUDg4SkVTbzY1UTZPMmxuelhreXExCnZvT1VFZlhONG9vdWRaekxsQnp5V1ptNFR4bk51djF4aGhSUkpkSHM0TFk2SkVkQm50ZStTZ0tXdlRiWTE1MXoKTVo1WjVGanlmREdPSDg3LzFjMWNuVk1BMEpkQm54NzdrZUNGbkN1MXN2S1Y2Qyt3NkFsbXBVOS9CM205alFsSwpWWE1ENWZpNnBpb1FBQmExNDVScGkzdjBZM3pKMElydjRNOUVYM0dqR2lsY0o1eURoSEtTMTJMNmJxMU9Oc2RxClYvb043eE5mQ0puZGthRFV5SDhhckR3SGhLUndTQTkrU2REYTdVTXM0R3cyc3Y3NjYvQ25MQmo4RExzY1RzZlQKaUdFb25VdXF2eWRXekF3K3FUc3ZURStvMHZsb2RFMG1UQ290ejRSVm95K0lvMVNDckNKdkdVUzkwWkRPVWU5aQpTVVd4czJpMFFnUGpxTXQ2V2pacU1vNEJGekMyMFRUVnI3aGZ3Y0tVTWxRNEw2blhBbHQvbCtremM3S0pDY1JmClFTb0Ntc1BYaHBPcUczNmhxZERlSDRLRW8vN2lkQjJ6SFFHUmM5SU9mT3RHSUw4TE9mTng1K0VpZDh2ekZhZGgKR2IrNnpGZEpLY29YMGR4V1dGc2M0WTU5Q2wwS3hKZXRPcTlwdWUzb2pRME9QK1BBVXpUbnFPVnVCMlRjbCs0eAptczRUamdQNW5YMjNSVHJMYlFGRld2elpvQWNERklXVjhMeEM0ZitYZEhxRUx6eXhvaFdkZUZnaFQ4V1B4ZitQClo3cExLUHdPaElmNnhYNnRmSlNTTUdiNm5paVJieGJmcWhyVkh4VjhRaTZmZkVMMEduRm1JMFg2emlzQ0F3RUEKQVFLQ0FnRUEwWThvZjc2d3duSWxYUjl0NzdnbmpZcDVQRldqZnNHUnRRV0dDdU1jeXJOV3JlVDVzbGZnUFFwQgpuOXQvYkVjM1UzYkZpdUFPeWZ4MGxKc09idEUzNS9XQ2syRjNRYTVUUnQ1aVp4TzJ5amEyRGF2R0EyZWxGRkxKCmc4VWVVN0w0MThNaWJWQmEwL2cwblRpVllacFR6dW93bFhacWxYcVZ5N1ZmbFRQVW8zaTRVcys2MGFLblZXQUQKREs4R1pDeVdvYlQ4WjllVnJEY3pxaGNTMWJ3aUZlbXdOMEx0Z3lVb1BGNU1IYmpZTmZxYjdPZkhGZk1pQmZVWQpiT1c1NStTVEwyUVo5R3JPbGFtZk5Ibk9QdjVPbUE2VnlKQm5QandkazJTeE1RZElUWk5wMnVUaEFZN0JGSU9TCkZPSlpoWG1PUEh2NzBUaVpqSWRuSmhyN3NKZG5ZK2htTk1QbSs1YTZOY28xaHJiSllxbldEQ0VMRVk0Vi9mSGYKZHdOZFZCckF1SE40STM5SC9DZGlzWnVOMVY2a1NxdDhCNTRrWkE3TXpmSFNHVk5kWEE0SDlJM1FicFllTHN0eApqc0ZXcXpXc25lKytMSHYwcDMyUWZ1clNEbTBMVzFsQi9zdWhINTFzU1RiL2pXNVkwbHVsUzRSRlZ5YjR4bUhXCmV3Z01TL0JSdDFza3dBY2tzVVdDUTZuclFZRjhWZW54UnM1UlprY1YxeFNXMytyWGJBOS9sV3p6YVI4ZEI2b3cKNVFyZCtoWUMyYXBSTnpYUDF0Y3lwdVk3NDBINk8xZzBOS2gxb2hlZFhsdkdwMjN2UGZaNlZ1OWdkQzZzR1dwTgpONTkvYmdReE5PQmE5YnN1V2FCMDJtYWx6T1hmUU9nMTQ4bGI3aWZrNFJIYzFqY3hkUkVDZ2dFQkFQMFZ4TXBWCk5vZ0dVM3pabzVtQlVJeHNsZzlRbkRmMGZtTkM3MWUramwrVWJXNUpVZWxTY0R6SlAxakpidndhWEE2bVJRMDAKcXl3NGlEN1Juejl0ZWpEaUExdCs2eUhTYVJGcXExUW5sOVZlWEIra0FRdjNES1JVeFBtSTFpS2ljYjFjN0l5eAoxWFI2TWJNN2VMc1FhWVdpaXFsVi85REV2SVB2UTNOYkRpME51YW45N3cxY2habk81UEZCd3FCNlJKTEFPU015Cmpxbjk2RnZqcnBRb3M5THJUUWs3cDZWOFBNY0RsQnVVZWFhODRYOW9sTzJvZTJ3MmNCQ21NSnVkdmNTR3ZST1AKaEVOa1hXRUlaaWd1WWxHaDhrRHlFd08waGY0a2tkcnB5TXdUdFZLSjdaRmZOWHpIT0dVL0IxckVoYzgzYWpyVgpuS2EwNGpGNk1mc2s3dTBDZ2dFQkFQMmt5VWxmWFNSVTREWlRMNkYrdlFrOVVFTmpUVEVtOGJ2UnN0VlUyTXYrClhXT2F5c0NuaUE5ZXpMYnR5R2RGQnMwWGFMRDVzUkVOK0NRdE5xVG1WTmRQVHV5ekpTTnZReFlhYnIxU0EydlQKMUFZbE9ZanF2VFo4L0cwSG1UM3I2WHVldzdZZ0dZZEJZZnBnekZLUkUxazZSU2R6cWRhQnRUK0luaS9qc3h1RQp2N2x1VVRZYXY3TzFicExYSk4vdTl6MEtuYUthK05iOGFhaVN6bXR5NVFZRlJrK3ZYdWM4dXRSYUwvUis0NXB0Cml1NTc4b2gvbVdmSGhPY0x6b2lnbDVYVU01dStXak1mYy91d2I5Z1FRenVybEV5L1NSdGNTMVVDQjN0VVArS0QKaGxGeXZJbXBlOFAvMjk2R256TVF3MnNwbC9ldHdhUVJDUUtGOGJRWTluY0NnZ0VCQUo4aUtQTHdVYkdHQ01qZwpNRFk5VVdCNmhvQnF0MCtYdEVERnZhajJjSjg0dlBZenRBVjVpSWt3SVZ5Nmk4YUk3SWxwa3RHUzVHNlJ2Vm1DCmhSZGt4d2dsbE9iYkR3M2RONk56NXZhclRwVWpGOW50VFpzd1pBcVFJcXFrbDhCL1UvVTFrS2VHeWlqTERLVWUKSi9PM2hpSTQ2ZWMvNC9KcFFmL1RXaDRXaXZ0WlBmemRab3FJT3BsVHRqRGNvSHczWlJiQk55d2loZ0h0WFVVcQpESU9zZENXVFBvVW50V29nakRhMjBWSG1NZmZkbkF4NHZld1JuRW1Xa1RCbXp2bUtYZUJNdUdhc1B3WUEvWllkCnFkNXFDL2c0VkJMeUkzS1krQWV0QnVrWFJ1TExJYUFjaWZ4MldUTjBNTW00cis4cTB0aFFoOE1tdmJFMDIyVXcKNkd4NTlLRUNnZ0VCQU9oSHJYSTlHLzQyb0RILzBrSFIzK29ETldyUkdKTG51RDZwVmwyWld3VE5oOWE4bmVyNgpRVmJhR1IxNCtxcmdBczkxSFpIY3lEUDNHQVNCUjJhUjdLWlU0ZEZRYWJWZW9oQXUyclVUMDBBKytBODhyY2plCk43TWJtTXQ4UnZEM0I1WUhHZkhDeWI0Y3VVNWlzUnIzOHNFbTVNZXhXNXF1cEQ1dnJYWHJ6MDFuTDNEd1B2ME8KVi9xS0w1M1gydFFjY2x4N1NVcnRJdTgycnNnSzBYQ0RBb3VWN3dMd2RqZkxYTWsxWW05RWVNa21nakhPWHBoMApTaGRKRjBQRGd6dUozZWYvTWRmeDVZYWx5a0IzSHFXK2x1T2hTS2xVRCs0M2dtRngvMG9KS0l3V3FMNFVGZWIzCngva0JhZWdLWHVhVDluSS80QVNaSWhsTzVISmtHYW8xcGhjQ2dnRUFGTG5HWkVSUjRaUkdpS0NuSGs3bk1hM2UKUVpnTWluTjMzU2hpTE9jOGorRHZVc0J5ZTc4bDc1d2dvUU9pV2hKeWV1emtLTFdTSllsNEpqQllLY3lEdVd4QwpZNU12LzBFczBsc09IY2JnVXpNM2thdkNqWWY1ZlU5Rk9uWTI1RExsNTV2RVpOV2dFMXBXZENsY2IxN3ROamZECm9Ec2RBSkRMWHRDQmkvUkZOdUQ5UlB5elRDOXFsRjRuOVJkTHBGR3grUWd5dHJ4OENReVNwZ2xNdndYbzRFOXoKVHdxYXVaWEQ4QkI5bU52MVBHRXk5UXJLbE91aUNCMEluM1dOUUZtVzErWHdLa3ZSbVFBQTRocHdIakNWN0FnKwpuV1RFaWhBcm1rallpeS9VV0ZqRXVuNkt1WVZCbWdwTmRoc0NpOUNzdzFkZ2lkNHVrRFk2WStxeSsyVW9Vdz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
                    EOF
                    '''

                    // Kubeconfig dosyasını kullanarak Kubernetes komutlarını çalıştır
                    sh '''
                    export KUBECONFIG=kubeconfig
                    kubectl create configmap app-config --from-literal=VERSION=${version} --dry-run=client -o yaml | kubectl apply -f -
                    kubectl apply -f k8s/db-depl.yaml
                    kubectl apply -f k8s/webapp.depl.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'İşlem başarıyla tamamlandı. Mert & Şeyma'
        }
    }
}
