apiVersion: v1
kind: Service
metadata:
  name: devopscicd-service
spec:
  type: LoadBalancer
  selector:
    app: DevOpsCICD
  ports:
    - port: 80
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd
spec:
  selector:
    matchLabels:
      app: DevOpsCICD
  replicas: 1
  template:
    metadata:
      labels:
        app: DevOpsCICD
    spec:
      containers:
        - name: devopscicd
          image: mertcihanbayir/dockercicd:v1
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1234"
      imagePullSecrets:
        - name: regcred
