apiVersion: v1
kind: Service
metadata:
  name: devopscicd-service
spec:
  selector:
    app: devopscicd
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 31017
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd #devopscicd-deploy
  labels:
    app: devopscicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopscicd
  template:
    metadata:
      name: devopscicd
      labels:
        app: devopscicd
    spec:
      containers:
        - name: devopscicd
          image: mertcihanbayir/devopscicd:latest
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VERSION
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1234"
          ports:
            - containerPort: 9090
