apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd-v2
  labels:
    app: devopscicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopscicd
  template:
    metadata:
      labels:
        app: devopscicd
    spec:
      containers:
        - name: devopscicd
          image: mertcihanbayir/devopscicd
          ports:
            - containerPort: 9090
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VERSION
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1234"
      imagePullSecrets:
        - name: myregistrykey
