apiVersion: v1
kind: Service
metadata:
  name: devopscicd-service
spec:
  type: LoadBalancer
  selector:
    app: DevOpsCICD
  ports:
    - port: 80
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopscicd
  labels:
    app: DevOpsCICD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DevOpsCICD
  template:
    metadata:
      labels:
        app: DevOpsCICD
    spec:
      containers:
        - name: devopscicd
          image: mertcihanbayir/devopscicd:latest
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VERSION
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "1234"
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: regcred
