apiVersion: V1
kind: Service
metadata:
  name: DevOpsCICD-service
spec:
  type: LoadBalancer
  selector:
    app: DevOpsCICD
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOpsCICD
spec:
  selector:
    matchLabels:
      app: DevOpsCICD
  replicas: 1
  template:
    metadata:
      labels:
        app: DevOpsCICD
    spec:
      containers:
      - name: DevOpsCICD
        image: mertcihanbayir/dockercicd:latest
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: postgres
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: "1234"