apiVersion: v1
kind: Service
metadata:
  name: devopscicd-service
spec:
  selector:
    app: devopscicd
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 31017
      protocol: TCP
  type: NodePort
